apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: home_web
  name: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: home_web
  template:
    metadata:
      labels:
        app: home_web
    spec:
      containers:
        - image: nginx:latest
          name: nginx
          ports:
            - containerPort: 80