apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deploy_view_bind
subjects:
- kind: User
  name: deploy_view
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: deploy-pod-view
  apiGroup: rbac.authorization.k8s.io