apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deploy-pod-edit
rules:
  - apiGroups: [ "" ]
    resources: [ pods, deployments ]
    verbs: [ get, list, create, update, patch, delete, deletecollection ]