apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prod_edit_bind
subjects:
- kind: User
  name: prod_edit
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: prod-edit-role
  apiGroup: rbac.authorization.k8s.io